In [4]:
import numpy as np
import pandas as pd
import matplotlib as mlp
import matplotlib.pyplot as plt

In [5]:
iris_data = pd.read_csv("data-files/iris.csv")

In [6]:
iris_data.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [9]:
iris_data.columns[:4]

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width'], dtype='object')

In [10]:
# X = iris_data.iloc[:, :4].values
X = iris_data[iris_data.columns[:4]].values
y = iris_data['species'].values

In [11]:
X.shape, y.shape

((150, 4), (150,))

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [15]:
X_train.shape, np.unique(y_train, return_counts=True), np.unique(y_test, return_counts=True)

((120, 4),
 (array(['setosa', 'versicolor', 'virginica'], dtype=object),
  array([40, 40, 40], dtype=int64)),
 (array(['setosa', 'versicolor', 'virginica'], dtype=object),
  array([10, 10, 10], dtype=int64)))

In [16]:
from sklearn.naive_bayes import GaussianNB

In [17]:
model = GaussianNB()
model.fit(X_train, y_train)
model.score(X_train, y_train), model.score(X_test, y_test)

(0.9583333333333334, 0.9666666666666667)

In [21]:
v = np.mean(X_train, axis=0)

In [24]:
v

array([5.84166667, 3.04416667, 3.77083333, 1.20416667])

In [23]:
model.predict([v])

array(['versicolor'], dtype='<U10')