In [1]:
import numpy as np

In [2]:
a = np.array([[1, 2], [3, 4]])
print (a)

[[1 2]
 [3 4]]


In [4]:
a=np.array([1, 2, 3, 4, 5])
print (a)
a=np.array([1, 2, 3, 4, 5], ndmin=2)
print (a)

[1 2 3 4 5]
[[1 2 3 4 5]]


In [7]:
a = np.array([[1,2,3],[4,5,6]]) 
print (a.shape)
print(a)

(2, 3)
[[1 2 3]
 [4 5 6]]


In [6]:
a = np.array([[1,2,3],[4,5,6]]) 
a.shape = (3,2) 
print (a) 

[[1 2]
 [3 4]
 [5 6]]


In [8]:
a = np.arange(24) 
print(a.ndim)
print(a)
b = a.reshape(2,4,3) 
print(b.ndim)
print(b)

1
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
3
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [10]:
x = np.empty((3,2), dtype=int)
print(x)

[[1 2]
 [3 4]
 [5 6]]


In [11]:
x = np.zeros((5,), dtype="int")
print(x)

[0 0 0 0 0]


In [14]:
a = np.linspace(1.0, 2.0, num = 5, endpoint=True) 
print (a)

[1.   1.25 1.5  1.75 2.  ]


In [15]:
x = np.array([[ 0, 1, 2],[ 3, 4, 5],[ 6, 7, 8],[ 9, 10, 11]])

In [16]:
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [23]:
print(x > 5)
print(x[x > 5])

[[False False False]
 [False False False]
 [ True  True  True]
 [ True  True  True]]
[ 6  7  8  9 10 11]


In [24]:
a = np.array([np.nan, 1,2,np.nan,3,4,5])
print(np.isnan(a))
print(~np.isnan(a))
print(a[~np.isnan(a)])

[ True False False  True False False False]
[False  True  True False  True  True  True]
[1. 2. 3. 4. 5.]


In [26]:
a = np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]]) 
print(a.shape)
b = np.array([1.0,2.0,3.0]) 
print(b.shape)
print (a + b) # b를 (4, 3)으로 만들어서

(4, 3)
(3,)
[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]


In [27]:
import pandas as pd

In [28]:
data = [['Alex',10],['Bob',12],['Clarke',13]]
df = pd.DataFrame(data,columns=['Name','Age'])
print(df)

     Name  Age
0    Alex   10
1     Bob   12
2  Clarke   13


In [31]:
data = {'Name':['Tom', 'Jack', 'Steve', 'Ricky'],'Age':[28,34,29,42]}
df = pd.DataFrame(data)
print(df)

    Name  Age
0    Tom   28
1   Jack   34
2  Steve   29
3  Ricky   42


In [34]:
# df = {'one' : pd.Series([1, 2, 3], index=['a', 'b', 'c']), 
#       'two' : pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])}
df = {'one' : pd.Series([1, 2, 3]), 
      'two' : pd.Series([1, 2, 3, 4])}
df = pd.DataFrame(df)

In [40]:
df

one  two
0  1.0    1
1  2.0    2
2  3.0    3
3  NaN    4

In [42]:
df["one"]
df[["one", "two"]] # 데이터프레임의 인덱싱은 컬럼 인덱싱

one  two
0  1.0    1
1  2.0    2
2  3.0    3
3  NaN    4

In [44]:
# df["one":"two"]
df[0:3] # 데이터프레임의 슬라이싱은 행 슬라이싱

one  two
0  1.0    1
1  2.0    2
2  3.0    3

In [45]:
df.iloc[:3, :] # iloc : 행과 열 순서번호로 인덱싱, 슬라이싱

one  two
0  1.0    1
1  2.0    2
2  3.0    3

In [46]:
titanic_df = pd.read_csv('data-files/titanic_data.csv')

In [50]:
titanic_df.head()
print(titanic_df.shape)
print(titanic_df.columns)
titanic_df.describe()

(891, 12)
Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')


PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200