In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
from sklearn.datasets import load_breast_cancer

breast_cancer = load_breast_cancer()

In [4]:
breast_cancer.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [9]:
print( breast_cancer['data'].shape )
print( breast_cancer['target'].shape)
print( breast_cancer.target_names)
print( breast_cancer['feature_names'])

(569, 30)
(569,)
['malignant' 'benign']
['mean radius' 'mean texture' 'mean perimeter' 'mean area'
 'mean smoothness' 'mean compactness' 'mean concavity'
 'mean concave points' 'mean symmetry' 'mean fractal dimension'
 'radius error' 'texture error' 'perimeter error' 'area error'
 'smoothness error' 'compactness error' 'concavity error'
 'concave points error' 'symmetry error' 'fractal dimension error'
 'worst radius' 'worst texture' 'worst perimeter' 'worst area'
 'worst smoothness' 'worst compactness' 'worst concavity'
 'worst concave points' 'worst symmetry' 'worst fractal dimension']


In [10]:
breast_cancer.data[0]

array([1.799e+01, 1.038e+01, 1.228e+02, 1.001e+03, 1.184e-01, 2.776e-01,
       3.001e-01, 1.471e-01, 2.419e-01, 7.871e-02, 1.095e+00, 9.053e-01,
       8.589e+00, 1.534e+02, 6.399e-03, 4.904e-02, 5.373e-02, 1.587e-02,
       3.003e-02, 6.193e-03, 2.538e+01, 1.733e+01, 1.846e+02, 2.019e+03,
       1.622e-01, 6.656e-01, 7.119e-01, 2.654e-01, 4.601e-01, 1.189e-01])

In [11]:
from sklearn.neighbors import KNeighborsClassifier

In [20]:
knn_model = KNeighborsClassifier(n_neighbors=5)

knn_model.fit(X=breast_cancer.data, y=breast_cancer.target)

knn_model.predict([breast_cancer.data[1]]), breast_cancer.target[1]

(array([0]), 0)

In [21]:
from sklearn.model_selection import train_test_split

In [26]:
X_train, X_test, y_train, y_test = train_test_split(breast_cancer['data'], breast_cancer['target'], test_size=0.2, random_state=42)

In [27]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((455, 30), (114, 30), (455,), (114,))

In [30]:
knn_model2 = KNeighborsClassifier(n_neighbors=5)
knn_model2.fit(X_train, y_train)

print( knn_model2.predict(X_test[:2]), y_test[:2] )
print( (knn_model2.predict(X_test) == y_test).sum() / 114 )

[1 0] [1 0]
0.956140350877193


In [31]:
from sklearn.datasets import load_diabetes

In [32]:
diabetes = load_diabetes()

In [33]:
diabetes.keys()

dict_keys(['data', 'target', 'frame', 'DESCR', 'feature_names', 'data_filename', 'target_filename', 'data_module'])

In [35]:
print( diabetes['target'][:10] )
print( diabetes['feature_names'] )

[151.  75. 141. 206. 135.  97. 138.  63. 110. 310.]
['age', 'sex', 'bmi', 'bp', 's1', 's2', 's3', 's4', 's5', 's6']


In [36]:
X_train, X_test, y_train, y_test = train_test_split(diabetes['data'], diabetes['target'], random_state=42)

In [38]:
from sklearn.neighbors import KNeighborsRegressor

knn_model3 = KNeighborsRegressor(n_neighbors=5)
knn_model3.fit(X_train, y_train)

print( knn_model3.predict(X_test[:2]), y_test[:2] )

print( knn_model3.score(X_test, y_test) ) # R2

[125.6 160.2] [219.  70.]
0.44659346214225026


In [42]:
from sklearn.metrics import mean_squared_error

print( np.sqrt( mean_squared_error(y_test, knn_model3.predict(X_test)) ) )

print( y_test.mean())

55.31877155619498
145.54054054054055


In [50]:
from sklearn.ensemble import RandomForestRegressor

rf_model = RandomForestRegressor(max_depth=4)
rf_model.fit(X_train, y_train)
print( rf_model.score(X_test, y_test) )
print( np.sqrt( mean_squared_error(y_test, rf_model.predict(X_test)) ) )

0.497524754777936
52.71178461411423
